spring:
  application:
    name: malclean

  profiles:
    active: default

  config:
    name: malclean
    import: optional:configserver:http://localhost:8888

  datasource:
    url: jdbc:h2:tcp://localhost/~/malware
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        highlight_sql: true
        jdbc:
          batch_size: 100

  servlet:
    multipart:
      maxFileSize: 15MB
      maxRequestSize: 30MB

  data:
    web:
      pageable:
        one-indexed-parameters: true

  messages:
    basename: messages, errors

logging:
  level:
    com:
      malclean: DEBUG

    org:
      hibernate:
        type:
          descriptor:
            sql: trace
      springframework:
        jdbc:
          core:
            JdbcTemplate: DEBUG,
            StatementCreatorUtils: TRACE

server:
  port: 8080

  error:
    include-message: always

  tomcat:
    mbeanregistry:
      enabled: true # 톰캣  metrics

management:
  server:
    port: 9095

  endpoint:
    health:
      show-details: always

  endpoints:
    web:
      exposure:
        include: "*"

external-server:
  ai-model-server:
    base-url: http://AI-MODEL-SERVER

eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

---
spring:
  config:
    activate:
      on-profile: dev

---
spring:
  config:
    activate:
      on-profile: prod