spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/malware
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        highlight_sql: true
        jdbc:
          batch_size: 100

  servlet:
    multipart:
      maxFileSize: 15MB
      maxRequestSize: 30MB

  data:
    web:
      pageable:
        one-indexed-parameters: true

  messages:
    basename: messages, errors

logging:
  level:
    com:
      malclean: trace

    org:
      hibernate:
        type:
          descriptor:
            sql: trace
      springframework:
        jdbc:
          core:
            JdbcTemplate: DEBUG,
            StatementCreatorUtils: TRACE

server:
  error:
    include-message: always

external-server:
  ai-classification:
    base-url: http://localhost:8000


---
spring:
  config:
    activate:
      on-profile: dev

---
spring:
  config:
    activate:
      on-profile: prod